Director {
  Name = hq-srv-dir
  DIRport = 9101
  QueryFile = "/opt/bacula/scripts/query.sql"
  WorkingDirectory = "/opt/bacula/working"
  PidDirectory = "/opt/bacula/working"
  Maximum Concurrent Jobs = 10
  Password = "P@ssw0rd"
  Messages = Daemon
}

Job {
  Name = "Backup-HQ-SRV-ETC"
  Type = Backup
  Level = Full
  Client = hq-srv-fd
  FileSet = "ETC"
  Storage = HQ-CLI-Storage
  Pool = BackupPool
  Messages = Standard
  Priority = 10
}

FileSet {
  Name = "ETC"
  Include {
    Options {
      signature = MD5
    }
    File = /etc
  }
}

Client {
  Name = hq-srv-fd
  Address = 192.168.100.2
  FDPort = 9102
  Catalog = MyCatalog
  Password = "BaculaFD2027!"
}

Storage {
  Name = HQ-CLI-Storage
  Address = 192.168.20.2
  SDPort = 9103
  Password = "BaculaSD2027!"
  Device = FileStorage
  Media Type = File
}

Catalog {
  Name = MyCatalog
  dbname = "bacula"
  dbuser = "bacula"
  dbpassword = "P@ssw0rd"
  dbaddress = "127.0.0.1"
}

Pool {
  Name = BackupPool
  Pool Type = Backup
  Recycle = yes
  AutoPrune = yes
  Volume Retention = 30 days
  Maximum Volumes = 10
}

Messages {
  Name = Standard
  console = all, !skipped, !saved
  catalog = all, !skipped, !saved
}

Messages {
  Name = Daemon
  console = all, !skipped, !saved
}
