Director {
  Name = hq-srv-dir
  Password = "BaculaFD2027!"
}

FileDaemon {
  Name = hq-srv-fd
  FDport = 9102
  Working Directory = "/opt/bacula/working"
  Pid Directory = "/opt/bacula/working"
  Maximum Concurrent Jobs = 10
}

Messages {
  Name = Standard
  director = hq-srv-dir = all, !skipped, !restored
}
