Storage {
  Name = hq-cli-sd
  SDPort = 9103
  Working Directory = "/var/lib/bacula"
  Pid Directory = "/var/run"
  Maximum Concurrent Jobs = 10
}

Director {
  Name = hq-srv-dir
  Password = "BaculaSD2027!"
}

Device {
  Name = FileStorage
  Media Type = File
  Archive Device = /backup
  LabelMedia = yes
  Random Access = yes
  AutomaticMount = yes
  RemovableMedia = no
  AlwaysOpen = no
}

Messages {
  Name = Standard
  director = hq-srv-dir = all
}
